import { writeFile, readFile } from 'node:fs/promises';
import { questions, learningQuestions } from '../src/data/questions/index.js';
import { misconceptions } from '../src/data/misconceptions.js';
import { storyChapters } from '../src/data/story.js';
import { flashcards } from '../src/data/flashcards.js';
import { classModes } from '../src/data/class-modes.js';
import { matchingTasks } from '../src/data/matching.js';
import { packetMissions } from '../src/data/packet-missions.js';
import { layers } from '../src/data/layers.js';
import { hashText } from '../src/domain/random.js';
const meta = (q) => ({ id: q.id, layer: q.layer, type: q.type, difficulty: q.difficulty });
const content = `// Generated by scripts/catalog.mjs. Contains IDs and metadata, never answers.\nexport const questions = ${JSON.stringify(questions.map(meta))};\nexport const learningQuestions = ${JSON.stringify(learningQuestions.map(meta))};\nexport const questionById = new Map(learningQuestions.map(q => [q.id,q]));\nexport const misconceptions = ${JSON.stringify(misconceptions.map(({ questions, ...rest }) => ({ ...rest, questions: questions.map((q) => ({ id: q.id })) })))};\nexport const misconceptionQuestions = misconceptions.flatMap(c=>c.questions);\nexport const misconceptionByQuestion = new Map(misconceptions.flatMap(c=>c.questions.map(q=>[q.id,c])));\nexport const storyChapters = ${JSON.stringify(storyChapters.map(({ questions, scene, lesson, analogy, ...rest }) => ({ ...rest, questions: questions.map((q) => ({ id: q.id })) })))};\nexport const storyById = new Map(storyChapters.map(c=>[c.id,c]));\nexport const flashcards = ${JSON.stringify(flashcards.map((c) => ({ id: c.id })))};\n`;
const revision = hashText(
  JSON.stringify({ classModes, questions, matchingTasks, packetMissions, layers }),
);
const generated = [
  ['../src/data/progress-catalog.js', content],
  [
    '../src/data/class-revision.js',
    `// Generated by scripts/catalog.mjs. Fingerprint of the complete class content.\nexport const CLASS_REVISION = ${JSON.stringify(revision)};\n`,
  ],
];
for (const [file, text] of generated) {
  const path = new URL(file, import.meta.url);
  if (process.argv.includes('--check')) {
    if ((await readFile(path, 'utf8')) !== text)
      throw new Error('Catálogo desactualizado. Ejecuta npm run catalog.');
  } else await writeFile(path, text);
}
